[package]
name = "e2e"
edition.workspace = true
version = "0.6.0-rc.6"
publish = false

[dependencies]
pubky-testnet = { path = "../pubky-testnet" }
pubky-common = { path = "../pubky-common" }
tokio = { version = "1.47.1", features = ["full", "test-util"] }
tracing-subscriber = "0.3.20"
pkarr = { workspace = true }
bytes = "1.10.1"
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
eventsource-stream = "0.2"
futures = "0.3"
