[general]
signup_mode = "token_required"
user_storage_quota_mb = 0
database_url = "postgres://localhost:5432/pubky_homeserver"

[drive]
pubky_listen_socket = "127.0.0.1:6287"
icann_listen_socket = "127.0.0.1:6286"
rate_limits = []

[storage]
type = "file_system"

[admin]
listen_socket = "127.0.0.1:6288"
admin_password = "admin"

[pkdns]
public_ip = "127.0.0.1"
icann_domain = "localhost"
user_keys_republisher_interval = 14400 # 4 hours in seconds
dht_relay_nodes = ["https://pkarr.pubky.app", "https://pkarr.pubky.org"]

[logging]
level = "info"
module_levels = ["pubky_homeserver=debug", "tower_http=debug"]