[general]
signup_mode = "token_required"
lmdb_backup_interval_s = 0
user_storage_quota_mb = 0


[drive]
pubky_listen_socket = "127.0.0.1:6287"
icann_listen_socket = "127.0.0.1:6286"
rate_limits = []

[admin]
listen_socket = "127.0.0.1:6288"
admin_password = "admin"

[pkdns]
public_ip = "127.0.0.1"
icann_domain = "localhost"
user_keys_republisher_interval = 14400 # 4 hours in seconds
dht_relay_nodes = ["https://pkarr.pubky.app", "https://pkarr.pubky.org"]

[logging]

# The following params exist, but the default value is None. 
# See ./sample.config.toml for usage
# public_icann_http_port =
# dht_bootstrap_nodes =
# dht_request_timeout_ms =
