[package]
name = "pubky-testnet"
version = "0.1.2"
edition = "2021"
authors = ["Nuh <nuh@nuh.dev>"]
description = "A local test network for Pubky Core development."
license = "MIT"
homepage = "https://github.com/pubky/pubky-core"
repository = "https://github.com/pubky/pubky-core"
keywords = ["pkarr", "pubky", "testnet", "testing"]
categories = ["web-programming", "authentication", "cryptography"]

[dependencies]
anyhow = "1.0.95"
http-relay = "0.2.0"
mainline = "5.2.0"
pkarr-relay = "0.5.7"
tokio = { version = "1.43.0", features = ["full"] }
tracing-subscriber = "0.3.19"
url = "2.5.4"

pubky = { version = "0.4.2", path = "../pubky-client" }
pubky-common = { version = "0.3.1", path = "../pubky-common" }
pubky-homeserver = { version = "0.1.2", path = "../pubky-homeserver" }

[dev-dependencies]
tracing-subscriber = "0.3.19"
