[package]
name = "pubky-testnet"
description = "A local test network for Pubky Core development."
version = "0.5.4"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true


keywords = ["pkarr", "pubky", "testnet", "testing"]
categories = ["web-programming", "authentication", "cryptography"]

[dependencies]
anyhow = "1.0.95"
pkarr-relay = { workspace = true }
tokio = { version = "1.43.0", features = ["full"] }
tracing-subscriber = "0.3.19"
url = "2.5.4"

pubky = { path = "../pubky-client", version = "0.5.4" }
pubky-common = { path = "../pubky-common", version = "0.5.4" }
pubky-homeserver = { path = "../pubky-homeserver", version = "0.5.4", default-features = false, features = [
    "testing",
] }
http-relay = { path = "../http-relay", version = "0.5.1" }
tempfile = "3.19.1"
tracing = "0.1.41"
pkarr = { workspace = true }
mainline = { workspace = true }
clap = "4.5.36"
dirs = "6.0.0"
